# Generated by Django 4.2.7 on 2024-01-09 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orphans', '0005_orphan_created_at_orphan_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('went_with', models.CharField(blank=True, max_length=100, null=True, verbose_name='Person Went With')),
                ('arrived_with', models.CharField(blank=True, max_length=100, null=True, verbose_name='Person Arrived With')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphans.orphan')),
            ],
        ),
    ]
