# Generated by Django 4.2.7 on 2023-12-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('address', models.TextField()),
                ('notes', models.TextField()),
                ('family_status', models.CharField(blank=True, choices=[('father_died', 'Father Died'), ('mother_died', 'Mother Died'), ('both_parents_died', 'Both Parents Died'), ('broken_family', 'Broken Family'), ('poor_family', 'Poor Family'), ('single_parent', 'Single Parent'), ('orphanage_care', 'Orphanage Care'), ('living_with_relatives', 'Living with Relatives'), ('abandoned', 'Abandoned'), ('adopted', 'Adopted'), ('divorced_parents', 'Divorced Parents'), ('separated_parents', 'Separated Parents'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=25, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('special_needs', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
