# Generated by Django 4.2.7 on 2024-01-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('2nd_vice_president', '2nd Vice President'), ('general_secretary', 'General Secretary'), ('joint_secretary', 'Joint Secretary'), ('publication_secretary', 'Publication Secretary'), ('finance_secretary', 'Finance Secretary'), ('executive_member', 'Executive Member'), ('general_member', 'General Member')], max_length=50),
        ),
    ]
